import fs from "node:fs";import path from "node:path";import {TOOL,STAGING,existingIds,writeJson} from "./lib.mjs";
const name=process.argv[2],limit=Number(process.argv[3]||100),offset=Number(process.argv[4]||0);if(!name)throw new Error("Usage: generic-profile.mjs <profile> [limit] [offset]");
const file=path.join(TOOL,"profiles/catalog",name+".json");if(!fs.existsSync(file))throw new Error("Unknown catalog profile: "+name);const p=JSON.parse(fs.readFileSync(file,"utf8"));
const cls=p.selector.instanceOf,pathExpr=p.selector.includeSubclasses?"wdt:P31/wdt:P279*":"wdt:P31";const q=`SELECT DISTINCT ?item ?itemLabel WHERE { ?item ${pathExpr} wd:${cls} . SERVICE wikibase:label { bd:serviceParam wikibase:language "${(p.languagePriority||["pl","en"]).join(",")}"; ?item rdfs:label ?itemLabel. } } ORDER BY ?item LIMIT ${limit} OFFSET ${offset}`;
const headers={Accept:"application/sparql-results+json","User-Agent":"ZapytajHankiBrainImporter/0.4 (https://zapytajhanki.com)"};async function run(q){for(let a=1;a<=3;a++){const r=await fetch("https://query.wikidata.org/sparql?query="+encodeURIComponent(q),{headers});if(r.ok)return r.json();if(![429,502,503,504].includes(r.status)||a===3)throw new Error("Wikidata HTTP "+r.status);await new Promise(x=>setTimeout(x,a*2000));}}
const data=await run(q),ids=existingIds();let accepted=0,duplicates=0,rejected=0;
const propLabels={P17:"państwo",P2044:"wysokość",P625:"współrzędne",P403:"ujście",P2043:"długość",P2046:"powierzchnia",P569:"data urodzenia",P570:"data śmierci",P19:"miejsce urodzenia",P106:"zawód",P585:"data",P276:"miejsce",P580:"początek",P582:"koniec",P710:"uczestnik",P571:"data założenia",P159:"siedziba",P856:"oficjalna strona",P50:"autor",P577:"data publikacji",P407:"język",P57:"reżyser",P495:"kraj pochodzenia",P1086:"liczba atomowa",P246:"symbol",P274:"wzór",P2067:"masa",P2120:"promień",P238:"kod IATA",P131:"jednostka administracyjna",P1082:"liczba ludności"};
for(const row of data.results.bindings){const uri=row.item?.value,label=row.itemLabel?.value;if(!uri||!label){rejected++;continue}const qid=uri.split("/").pop(),id=p.name+"-"+qid.toLowerCase();if(ids.has(id)){duplicates++;continue}let countryCode=null;try{const cd=await run(`SELECT ?code WHERE { wd:${qid} wdt:P17 ?country . ?country wdt:P297 ?code . } LIMIT 1`);countryCode=cd.results.bindings[0]?.code?.value?.toUpperCase()||null}catch{}if(!countryCode||!/^[A-Z]{2}$/.test(countryCode)){rejected++;console.warn(name+" "+qid+": held because canonical schema requires a real ISO country code.");continue}const vals=[];for(const prop of p.properties){const eq=`SELECT ?v ?vLabel WHERE { wd:${qid} wdt:${prop} ?v . SERVICE wikibase:label { bd:serviceParam wikibase:language "${(p.languagePriority||["pl","en"]).join(",")}"; ?v rdfs:label ?vLabel. } } LIMIT 3`;try{const d=await run(eq);const a=d.results.bindings.map(x=>x.vLabel?.value||x.v?.value).filter(Boolean);if(a.length)vals.push([prop,a])}catch(e){console.warn(name+" "+qid+" "+prop+": "+e.message)}}if(!vals.length){rejected++;continue}
const facts=[label+" — rekord wiedzy w kategorii „"+p.subtopic+"”."].concat(vals.map(([prop,a])=>(propLabels[prop]||prop)+": "+a.join(", ")+"."));const sources=["https://www.wikidata.org/wiki/"+qid];const record={id,country:countryCode,jurisdiction:"general",region:"WORLD",topic:p.topic,subtopic:p.subtopic,title:label,facts,effective_from:null,effective_to:null,last_verified:new Date().toISOString().slice(0,10),official_sources:sources,related_public_pages:[]};writeJson(path.join(STAGING,p.output||p.name,id+".json"),record);ids.add(id);accepted++}
console.log(JSON.stringify({profile:name,rowsReceived:data.results.bindings.length,accepted,duplicates,rejected,staging:path.join(STAGING,p.output||p.name)},null,2));
