import fs from "node:fs";import path from "node:path";import {TOOL,STAGING,existingIds,writeJson} from "./lib.mjs";
const name=process.argv[2],limit=Number(process.argv[3]||100),offset=Number(process.argv[4]||0);if(!name)throw new Error("Usage: generic-profile.mjs <profile> [limit] [offset]");
const file=path.join(TOOL,"profiles/catalog",name+".json");if(!fs.existsSync(file))throw new Error("Unknown catalog profile: "+name);const p=JSON.parse(fs.readFileSync(file,"utf8"));
const cls=p.selector.instanceOf,pathExpr=p.selector.includeSubclasses?"wdt:P31/wdt:P279*":"wdt:P31",langs=(p.languagePriority||["pl","en"]).join(",");
const headers={Accept:"application/sparql-results+json","User-Agent":"ZapytajHankiBrainImporter/0.5 (https://zapytajhanki.com)"};
async function run(q){for(let a=1;a<=4;a++){const r=await fetch("https://query.wikidata.org/sparql?query="+encodeURIComponent(q),{headers});if(r.ok)return r.json();if(![429,502,503,504].includes(r.status)||a===4)throw new Error("Wikidata HTTP "+r.status);await new Promise(x=>setTimeout(x,a*1500));}}
const selectQ=`SELECT DISTINCT ?item ?itemLabel WHERE { ?item ${pathExpr} wd:${cls} . SERVICE wikibase:label { bd:serviceParam wikibase:language "${langs}". } } ORDER BY ?item LIMIT ${limit} OFFSET ${offset}`;
const selected=await run(selectQ),items=selected.results.bindings.map(x=>({uri:x.item?.value,label:x.itemLabel?.value,qid:x.item?.value?.split("/").pop()})).filter(x=>x.uri&&x.label&&/^Q\\d+$/.test(x.qid));
const ids=existingIds();let accepted=0,duplicates=0,rejected=0;if(!items.length){console.log(JSON.stringify({profile:name,rowsReceived:0,accepted,duplicates,rejected},null,2));process.exit(0)}
const values=items.map(x=>"wd:"+x.qid).join(" ");
const propValues=new Map(),countries=new Map(),sources=new Map();
const props=p.properties.join(" ");
const propQ=`SELECT ?item ?prop ?v ?vLabel WHERE { VALUES ?item { ${values} } VALUES ?prop { ${props.split(" ").map(x=>"wdt:"+x).join(" ")} } ?item ?prop ?v . SERVICE wikibase:label { bd:serviceParam wikibase:language "${langs}". } }`;
const pd=await run(propQ);for(const x of pd.results.bindings){const qid=x.item.value.split("/").pop(),prop=x.prop.value.split("/").pop(),v=x.vLabel?.value||x.v?.value;if(!v)continue;const k=qid+"|"+prop;if(!propValues.has(k))propValues.set(k,[]);if(propValues.get(k).length<3&&!propValues.get(k).includes(v))propValues.get(k).push(v)}
const countryQ=`SELECT ?item ?code WHERE { VALUES ?item { ${values} } ?item wdt:P17 ?country . ?country wdt:P297 ?code . }`;try{const d=await run(countryQ);for(const x of d.results.bindings){const q=x.item.value.split("/").pop(),v=x.code?.value?.toUpperCase();if(/^[A-Z]{2}$/.test(v||"")&&!countries.has(q))countries.set(q,v)}}catch(e){console.warn("country batch: "+e.message)}
const sourceQ=`SELECT DISTINCT ?item ?url WHERE { VALUES ?item { ${values} } ?item ?p ?statement . ?statement prov:wasDerivedFrom ?ref . ?ref pr:P854 ?url . }`;try{const d=await run(sourceQ);for(const x of d.results.bindings){const q=x.item.value.split("/").pop(),u=x.url?.value;if(!u)continue;if(!sources.has(q))sources.set(q,[]);if(sources.get(q).length<10&&!sources.get(q).includes(u))sources.get(q).push(u)}}catch(e){console.warn("source batch: "+e.message)}
const propLabels={P17:"państwo",P2044:"wysokość",P625:"współrzędne",P403:"ujście",P2043:"długość",P2046:"powierzchnia",P569:"data urodzenia",P570:"data śmierci",P19:"miejsce urodzenia",P106:"zawód",P585:"data",P276:"miejsce",P580:"początek",P582:"koniec",P710:"uczestnik",P571:"data założenia",P159:"siedziba",P856:"oficjalna strona",P50:"autor",P577:"data publikacji",P407:"język",P57:"reżyser",P495:"kraj pochodzenia",P1086:"liczba atomowa",P246:"symbol",P274:"wzór",P2067:"masa",P2120:"promień",P238:"kod IATA",P131:"jednostka administracyjna",P1082:"liczba ludności"};
const score=u=>{try{const h=new URL(u).hostname.toLowerCase();if(/(\\.gov|\\.gov\\.|\\.gouv\\.|\\.gob\\.|\\.go\\.|\\.edu$|\\.edu\\.)/.test(h)||/(stat|statistics|census)/.test(h))return 4;if(/(un\\.org|worldbank\\.org|oecd\\.org|europa\\.eu)/.test(h))return 3;if(h.includes("wikidata.org"))return 1;return 2}catch{return 0}};
for(const item of items){const {qid,label}=item,id=p.name+"-"+qid.toLowerCase();if(ids.has(id)){duplicates++;continue}const by={};for(const prop of p.properties){const a=propValues.get(qid+"|"+prop);if(a?.length)by[prop]=a}if(!Object.keys(by).length){rejected++;continue}const one=k=>by[k]?.[0],all=k=>by[k]?.join(", "),facts=[],add=x=>x&&facts.push(x);
if(p.family==="places"){add(one("P17")?label+" znajduje się w państwie "+one("P17")+".":null);add(one("P2044")?"Wysokość: "+one("P2044")+".":null);add(one("P2043")?"Długość: "+one("P2043")+".":null);add(one("P2046")?"Powierzchnia: "+one("P2046")+".":null);add(one("P403")?"Ujście: "+one("P403")+".":null)}
else if(p.family==="people"){add(one("P569")?"Data urodzenia: "+one("P569")+".":null);add(one("P570")?"Data śmierci: "+one("P570")+".":null);add(all("P106")?"Zawód lub dziedzina działalności: "+all("P106")+".":null);add(one("P19")?"Miejsce urodzenia: "+one("P19")+".":null)}
else if(p.family==="events"){add(one("P585")?"Data wydarzenia: "+one("P585")+".":null);add(one("P580")?"Początek: "+one("P580")+".":null);add(one("P582")?"Koniec: "+one("P582")+".":null);add(one("P276")?"Miejsce: "+one("P276")+".":null);add(all("P710")?"Uczestnicy: "+all("P710")+".":null)}
else if(p.family==="organizations"){add(one("P571")?"Data założenia: "+one("P571")+".":null);add(one("P159")?"Siedziba: "+one("P159")+".":null);add(one("P17")?"Państwo: "+one("P17")+".":null)}
else if(p.family==="works"){add(all("P50")?"Autor: "+all("P50")+".":null);add(all("P57")?"Reżyser: "+all("P57")+".":null);add(one("P577")?"Data publikacji lub premiery: "+one("P577")+".":null);add(all("P407")?"Język: "+all("P407")+".":null);add(one("P495")?"Kraj pochodzenia: "+one("P495")+".":null)}
else if(p.family==="concepts"){add(one("P1086")?"Liczba atomowa: "+one("P1086")+".":null);add(one("P246")?"Symbol: "+one("P246")+".":null);add(one("P274")?"Wzór: "+one("P274")+".":null);add(one("P2067")?"Masa: "+one("P2067")+".":null);add(one("P2120")?"Promień: "+one("P2120")+".":null)}
else if(p.family==="infrastructure"){add(one("P17")?"Państwo: "+one("P17")+".":null);add(one("P238")?"Kod IATA: "+one("P238")+".":null);add(one("P131")?"Jednostka administracyjna: "+one("P131")+".":null);add(one("P2043")?"Długość: "+one("P2043")+".":null)}
else if(p.family==="statistics"){add(one("P1082")?"Liczba ludności: "+one("P1082")+".":null);add(one("P585")?"Data obserwacji: "+one("P585")+".":null)}
if(!facts.length)for(const [prop,a] of Object.entries(by))facts.push((propLabels[prop]||prop)+": "+a.join(", ")+".");
let src=[...(sources.get(qid)||[])].sort((a,b)=>score(b)-score(a)).slice(0,5);if(!src.length)src=["https://www.wikidata.org/wiki/"+qid];
const record={id,country:countries.get(qid)||"GLOBAL",jurisdiction:"general",region:"WORLD",topic:p.topic,subtopic:p.subtopic,title:label,facts,effective_from:null,effective_to:null,last_verified:new Date().toISOString().slice(0,10),official_sources:src,related_public_pages:[]};writeJson(path.join(STAGING,p.output||p.name,id+".json"),record);ids.add(id);accepted++}
console.log(JSON.stringify({profile:name,rowsReceived:items.length,accepted,duplicates,rejected,staging:path.join(STAGING,p.output||p.name)},null,2));
