import fs from "node:fs";import path from "node:path";import {spawn} from "node:child_process";import {TOOL,writeJson} from "./lib.mjs";
const manifest=JSON.parse(fs.readFileSync(path.join(TOOL,"profiles/manifest.json"),"utf8")),requested=process.argv.slice(2);
const profiles=manifest.profiles.filter(p=>p.enabled&&(!requested.length||requested.includes(p.name)||requested.includes(p.family)));if(!profiles.length)throw new Error("No enabled profiles matched.");
const CONCURRENCY=Math.max(1,Number(process.env.HANKA_IMPORT_CONCURRENCY||4)),TIMEOUT=Math.max(10000,Number(process.env.HANKA_PROFILE_TIMEOUT_MS||90000));
function execute(p,offset){return new Promise(resolve=>{const args=["import.mjs","generic-profile.mjs"].includes(p.runner)?[path.join(TOOL,"src",p.runner),p.name,String(p.batchSize),String(offset)]:[path.join(TOOL,"src",p.runner),String(p.batchSize),String(offset)];const child=spawn(process.execPath,args,{stdio:["ignore","pipe","pipe"]});let stdout="",stderr="",timedOut=false;child.stdout.on("data",d=>stdout+=d);child.stderr.on("data",d=>stderr+=d);const timer=setTimeout(()=>{timedOut=true;child.kill("SIGKILL")},TIMEOUT);child.on("close",(code,signal)=>{clearTimeout(timer);resolve({code,signal,stdout,stderr,timedOut})});child.on("error",e=>{clearTimeout(timer);resolve({code:1,stdout,stderr:stderr+"\n"+e.message,timedOut})})})}
const num=(s,k)=>{const a=[...s.matchAll(new RegExp('"'+k+'"\\s*:\\s*(\\d+)','g'))].at(-1);return a?Number(a[1]):0};
async function processProfile(p){let pages=0,received=0,accepted=0,duplicates=0,rejected=0,status="ok";const runs=[],failures=[];for(let offset=0;pages<p.maxPages;offset+=p.batchSize){const r=await execute(p,offset);pages++;if(r.stdout)process.stdout.write("["+p.name+"] "+r.stdout);if(r.stderr)process.stderr.write("["+p.name+"] "+r.stderr);if(r.timedOut||r.code!==0){status=r.timedOut?"timeout":"failed";failures.push({profile:p.name,offset,exitCode:r.code,signal:r.signal||null,timeout:r.timedOut,error:(r.stderr||"").trim().slice(-1500)});runs.push({profile:p.name,offset,status});break}runs.push({profile:p.name,offset,status:"ok"});const got=num(r.stdout,"rowsReceived")||num(r.stdout,"received");received+=got;accepted+=num(r.stdout,"accepted");duplicates+=num(r.stdout,"duplicates");rejected+=num(r.stdout,"rejected");if(got===0||got<p.batchSize)break}return {summary:{profile:p.name,family:p.family,status,pages,received,accepted,duplicates,rejected},runs,failures}}
const results=new Array(profiles.length);let cursor=0;async function worker(){while(true){const i=cursor++;if(i>=profiles.length)return;results[i]=await processProfile(profiles[i])}}await Promise.all(Array.from({length:Math.min(CONCURRENCY,profiles.length)},()=>worker()));
const profileSummary=results.map(x=>x.summary),runs=results.flatMap(x=>x.runs),failures=results.flatMap(x=>x.failures);
const report={generated:new Date().toISOString(),concurrency:CONCURRENCY,profileTimeoutMs:TIMEOUT,orchestrated:profiles.map(p=>p.name),profiles:profileSummary,runs:runs.length,successfulRuns:runs.filter(x=>x.status==="ok").length,failedRuns:failures.length,failures};writeJson(path.join(TOOL,"orchestration-report.json"),report);console.log(JSON.stringify(report,null,2));
