import fs from "node:fs";import path from "node:path";import Ajv2020 from "ajv/dist/2020.js";import addFormats from "ajv-formats";import {ROOT,TOOL,STAGING,walk,slug,writeJson} from "./lib.mjs";
const schema=JSON.parse(fs.readFileSync(path.join(ROOT,"brain/schema/knowledge-record.schema.json"),"utf8"));const ajv=new Ajv2020({allErrors:true,strict:false});addFormats(ajv);const validate=ajv.compile(schema);
const qidOf=j=>{const m=(j.official_sources||[]).join(" ").match(/wikidata\.org\/wiki\/(Q\d+)/i);return m?.[1]?.toUpperCase()||null};const canonical=[];for(const f of walk(path.join(ROOT,"brain"))){try{const j=JSON.parse(fs.readFileSync(f,"utf8"));if(j.id)canonical.push({file:f,id:j.id,title:j.title||"",topic:j.topic||"",subtopic:j.subtopic||"",country:j.country||"",qid:qidOf(j)})}catch{}}
const norm=s=>slug(String(s||""));const sourceScore=u=>{try{const h=new URL(u).hostname.toLowerCase();if(/(\.gov|\.gov\.|\.gouv\.|\.gob\.|\.go\.|\.edu$|\.edu\.)/.test(h)||/(stat|statistics|census)/.test(h))return 4;if(/(un\.org|worldbank\.org|oecd\.org|europa\.eu)/.test(h))return 3;if(h==="www.wikidata.org"||h==="wikidata.org")return 1;return 2}catch{return 0}};
const stagedTitle=new Map(),stagedQid=new Map();
const broadProfiles=new Set(["airports","bridges","universities","films","books","artists","scientists","writers","lakes","rivers","islands","planets","chemical-elements"]);
const trustedScore=3;const report={generated:new Date().toISOString(),summary:{total:0,pass:0,hold:0},records:[]};
for(const f of walk(STAGING)){let j;try{j=JSON.parse(fs.readFileSync(f,"utf8"))}catch{report.summary.total++;report.summary.hold++;report.records.push({file:f,status:"hold",reasons:["invalid-json"]});continue}report.summary.total++;const reasons=[];if(!validate(j))reasons.push("schema-invalid");const sameId=canonical.find(x=>x.id===j.id);if(sameId)reasons.push("canonical-id-exists");const qid=qidOf(j);if(qid&&canonical.some(x=>x.qid===qid))reasons.push("canonical-entity-exists:"+qid);const nt=norm(j.title);if(!nt||/^q\d+$/.test(nt))reasons.push("unusable-title");const titleKey=nt+"|"+(j.country||"");if(stagedTitle.has(titleKey))reasons.push("staged-title-overlap:"+stagedTitle.get(titleKey));else stagedTitle.set(titleKey,j.id);if(qid&&stagedQid.has(qid))reasons.push("staged-entity-overlap:"+stagedQid.get(qid));else if(qid)stagedQid.set(qid,j.id);const overlaps=canonical.filter(x=>norm(x.title)===nt&&x.topic===j.topic&&(x.country===j.country||x.country==="GLOBAL"||j.country==="GLOBAL"));if(overlaps.length)reasons.push("semantic-title-overlap:"+overlaps.slice(0,3).map(x=>x.id).join(","));const scores=(j.official_sources||[]).map(sourceScore);const best=scores.length?Math.max(...scores):0;if(!scores.length||best<2)reasons.push("weak-source-only");const profile=path.relative(STAGING,f).split(path.sep)[0];if(broadProfiles.has(profile)&&best<trustedScore)reasons.push("brain-worthiness-unproven");if((j.facts||[]).some(x=>/T00:00:00Z|\bQ\d+\b/.test(x)))reasons.push("raw-machine-value");if((j.facts||[]).some(x=>/rekord wiedzy w kategorii/i.test(x)))reasons.push("generic-placeholder-fact");const status=reasons.length?"hold":"pass";report.summary[status]++;report.records.push({file:path.relative(STAGING,f),id:j.id,title:j.title,status,reasons,sourceScore:best});}
const out=path.join(TOOL,"review-report.json");writeJson(out,report);console.log(JSON.stringify(report.summary,null,2));console.log("Review report: "+out);if(report.summary.hold)process.exitCode=2;
