(()=>{'use strict';const KEY='zh-uscis-2025-mcq-live-v5',URL='/testy/obywatelstwo-usa/questions-2025.json';let bank=[],session=null;const $=id=>document.getElementById(id),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(session))}catch(e){}};const show=h=>{$('test-app').innerHTML=h;$('test-app').scrollIntoView({behavior:'smooth',block:'start'})};const count=()=>Object.values(session.answers),good=()=>count().filter(x=>x.correct===true).length,bad=()=>count().filter(x=>x.correct===false).length;const question=id=>bank[id-1];const makeOptions=q=>{const correct=q.acceptedAnswers[0];const pool=(q.distractors||[]).filter(a=>a!==correct&&!q.acceptedAnswers.includes(a));const options=[correct];for(const a of pool){if(options.length===4)break;if(!options.some(v=>v.toLowerCase()===a.toLowerCase()))options.push(a)}return shuffle(options)};const start=mode=>{const ids=mode==='full'?bank.map(q=>q.id):shuffle(bank.filter(q=>q.answerMode!=='dynamic').map(q=>q.id)).slice(0,20);session={mode,ids,index:0,answers:{},options:{}};save();renderQuestion()};const home=()=>{let old=null;try{old=JSON.parse(localStorage.getItem(KEY))}catch(e){}
show('<div class="test-panel quiz-home"><div class="quiz-home-top"><span class="quiz-pill">USCIS 2025</span><span class="quiz-pill quiz-pill-soft">Bez logowania</span></div><h2>Gotowy na obywatelstwo?</h2><p class="quiz-home-lede">Sprawdź swoją wiedzę. Pytania po angielsku, tłumaczenia po polsku.</p><div class="quiz-mode-grid"><button type="button" class="quiz-mode" id="mock"><span class="quiz-mode-icon">↗</span><span><strong>Egzamin próbny</strong><small>20 losowych pytań · próg 12 poprawnych</small></span><span class="quiz-mode-arrow">→</span></button><button type="button" class="quiz-mode" id="full"><span class="quiz-mode-icon">◎</span><span><strong>Pełny trening</strong><small>128 pytań · ucz się we własnym tempie</small></span><span class="quiz-mode-arrow">→</span></button></div>'+(old?.ids?.length?'<button type="button" class="quiz-resume" id="resume">↺ Wznów poprzedni test</button>':'')+'<p class="quiz-home-note">Prawdziwy egzamin USCIS jest ustny. Odpowiedzi do wyboru są materiałem do ćwiczeń.</p></div>');
$('full').onclick=()=>start('full');$('mock').onclick=()=>start('mock');if($('resume'))$('resume').onclick=()=>{session=old;renderQuestion()}};const renderQuestion=()=>{if(!session)return home();const entries=count();if(session.index>=session.ids.length||(session.mode==='mock'&&(good()>=12||bad()>=9)))return results();const id=session.ids[session.index],q=question(id);if(q.answerMode==='single'&&!session.options[id]){session.options[id]=makeOptions(q);save()}const chosen=session.answers[id];if(q.answerMode==='dynamic')return renderDynamic(q,id,chosen);if(q.answerMode==='multi')return renderMulti(q,id,chosen);const buttons=session.options[id].map((a,i)=>'<button type="button" class="quiz-option'+(chosen?(a===chosen.selected?' selected':''):'')+'" data-option="'+i+'" '+(chosen?'disabled':'')+'><span class="quiz-letter">'+String.fromCharCode(65+i)+'</span><span>'+escape(a)+'</span></button>').join('');show('<div class="test-panel quiz-card"><div class="test-small">'+(session.mode==='full'?'Pełny trening':session.mode==='mock'?'Egzamin próbny':'Powtórka błędów')+' · Pytanie '+(session.index+1)+' z '+session.ids.length+'</div><div class="test-track"><div style="width:'+Math.round(100*session.index/session.ids.length)+'%"></div></div><h2>'+escape(q.question)+'</h2><p class="quiz-translation" lang="pl">'+escape(q.questionPl)+'</p><div class="quiz-options">'+buttons+'</div><div id="quiz-feedback"></div><p class="test-small">Wybierz odpowiedź. Pytania USCIS 2025 · nr '+id+'.</p></div>');if(!chosen){document.querySelectorAll('#test-app .quiz-option').forEach(btn=>btn.onclick=()=>select(id,session.options[id][Number(btn.dataset.option)]))}else feedback(id,chosen)};const select=(id,selected)=>{if(session.answers[id])return;const q=question(id),correct=q.acceptedAnswers.includes(selected);session.answers[id]={selected,correct};save();renderQuestion()};const advance=()=>{session.index++;save();renderQuestion()};
const renderDynamic=(q,id,chosen)=>{
const url='https://www.uscis.gov/citizenship/testupdates';
show('<div class="test-panel quiz-card"><div class="test-small">Pełny trening · Pytanie '+(session.index+1)+' z '+session.ids.length+'</div><h2>'+escape(q.question)+'</h2><p class="quiz-translation">'+escape(q.questionPl)+'</p><p><strong>Pytanie zależne od stanu lub aktualnego urzędnika.</strong> Nie jest oceniane automatycznie. Sprawdź aktualną odpowiedź przed egzaminem.</p><p><a href="'+url+'" target="_blank" rel="noopener">Oficjalne aktualizacje USCIS ↗</a></p><button type="button" class="test-action" id="dyn-next">Dalej — bez punktacji →</button></div>');
$('dyn-next').onclick=()=>{session.answers[id]={selected:null,correct:null,ungraded:true};advance()}
};
const renderMulti=(q,id,chosen)=>{
const needed=q.requiredAnswers;
if(!session.options[id]||session.options[id].filter(a=>q.acceptedAnswers.includes(a)).length<needed){const correct=shuffle(q.acceptedAnswers).slice(0,Math.max(needed,3));session.options[id]=shuffle([...correct,...q.distractors]);save()}
const opts=session.options[id];
const picked=Array.isArray(chosen?.selected)?chosen.selected:[];
show('<div class="test-panel quiz-card"><div class="test-small">'+(session.mode==='mock'?'Egzamin próbny':session.mode==='review'?'Powtórka błędów':'Pełny trening')+' · Pytanie '+(session.index+1)+' z '+session.ids.length+'</div><div class="test-track"><div style="width:'+Math.round(100*session.index/session.ids.length)+'%"></div></div><h2>'+escape(q.question)+'</h2><p class="quiz-translation">'+escape(q.questionPl)+'</p><p><strong>Wybierz dokładnie '+needed+' odpowiedzi.</strong></p><div class="quiz-options">'+opts.map((answer,i)=>'<label class="quiz-option"><input type="checkbox" class="multi-option" value="'+i+'" '+(picked.includes(answer)?'checked ':'')+(chosen?'disabled ':'')+'><span>'+escape(answer)+'</span></label>').join('')+'</div><button type="button" class="test-action" id="multi-check" '+(chosen?'disabled':'')+'>Sprawdź odpowiedzi</button><div id="multi-feedback"></div></div>');
$('multi-check').onclick=()=>{
const picks=[...document.querySelectorAll('#test-app .multi-option:checked')].map(el=>opts[Number(el.value)]);
if(picks.length!==needed){$('multi-feedback').textContent='Zaznacz dokładnie '+needed+' odpowiedzi.';return}
session.answers[id]={selected:picks,correct:picks.every(a=>q.acceptedAnswers.includes(a))};save();renderMulti(q,id,session.answers[id])
};
if(chosen){$('multi-feedback').innerHTML='<div class="quiz-result"><strong>'+(chosen.correct?'✓ Dobra odpowiedź!':'✕ Nie tym razem')+'</strong><p>Akceptowane odpowiedzi USCIS:</p><ul>'+q.acceptedAnswers.map(a=>'<li>'+escape(a)+'</li>').join('')+'</ul></div><button type="button" class="test-action" id="multi-next">Następne pytanie →</button>';$('multi-next').onclick=advance}
};
const feedback=(id,answer)=>{const q=question(id),correct=q.acceptedAnswers[0];document.querySelectorAll('#test-app .quiz-option').forEach(btn=>{const a=btn.querySelector('span:last-child')?.textContent;if(q.acceptedAnswers.includes(a))btn.classList.add('is-correct');else if(a===answer.selected)btn.classList.add('is-wrong')});$('quiz-feedback').innerHTML='<div class="quiz-result"><strong>'+(answer.correct?'✓ Dobra odpowiedź!':'✕ Nie tym razem')+'</strong><p>Akceptowane odpowiedzi USCIS:</p><ul>'+q.acceptedAnswers.map(a=>'<li>'+escape(a)+'</li>').join('')+'</ul></div><button type="button" class="test-action" id="next">'+(session.index===session.ids.length-1?'Zobacz wynik':'Następne pytanie →')+'</button>';$('next').onclick=()=>{session.index++;save();renderQuestion()}};const results=()=>{
const entries=count(),wrong=Object.entries(session.answers).filter(([id,v])=>v.correct===false).map(([id])=>Number(id)),n=entries.filter(x=>x.correct!==null).length,ungraded=entries.length-n,ok=good(),pct=Math.round(100*ok/Math.max(1,n)),mock=session.mode==='mock';
const outcome=mock?(ok>=12?'Próg zaliczony':bad()>=9?'Próg niezaliczony':'Test zakończony'):'Trening zakończony';
const report='Wynik testu obywatelskiego USCIS 2025 — Zapytaj Hanki\\nTryb: '+(mock?'Egzamin próbny':session.mode==='review'?'Powtórka błędów':'Pełny trening')+'\\nPoprawne: '+ok+' / '+n+' ('+pct+'%)'+(ungraded?'\\nBez punktacji: '+ungraded:'')+'\\nBłędne pytania: '+(wrong.length?wrong.map(id=>id+'. '+question(id).question).join('\\n'):'brak')+'\\nhttps://zapytajhanki.com/testy/obywatelstwo-usa/';
show('<div class="test-panel quiz-summary"><span class="quiz-pill">Twój wynik</span><h2>'+outcome+'</h2><div class="quiz-score"><strong>'+pct+'<small>%</small></strong><span>'+ok+' z '+n+' poprawnych'+(ungraded?'<br>'+ungraded+' pytań bez punktacji':'')+'</span></div><div class="quiz-summary-stats"><span><strong>'+ok+'</strong> Poprawne</span><span><strong>'+wrong.length+'</strong> Do powtórki</span></div><div class="test-actions"><button type="button" class="test-action" id="review" '+(wrong.length?'':'disabled')+'>↻ Powtórz błędy ('+wrong.length+')</button><button type="button" class="test-action test-outline" id="email">✉ Wyślij wynik e-mailem</button><button type="button" class="test-action test-outline" id="share">Udostępnij wynik</button><button type="button" class="quiz-resume" id="restart">Rozpocznij nowy test →</button></div>'+(wrong.length?'<details class="quiz-review-details"><summary>Zobacz listę błędnych pytań ('+wrong.length+')</summary><div class="quiz-review-list">'+wrong.map(id=>'<details><summary>'+id+'. '+escape(question(id).question)+'</summary><p>'+question(id).acceptedAnswers.map(escape).join(' · ')+'</p></details>').join('')+'</div></details>':'<p class="quiz-home-note">Nie masz pytań do powtórki. Brawo!</p>')+'<p class="quiz-home-note">E-mail otwiera Twoją aplikację pocztową. Wyniki nie są przechowywane na serwerze.</p></div>');
$('review').onclick=()=>{if(!wrong.length)return;session={mode:'review',ids:wrong,index:0,answers:{},options:{}};save();renderQuestion()};
$('restart').onclick=()=>{session=null;localStorage.removeItem(KEY);home()};
$('email').onclick=()=>{const subject='Mój wynik — test obywatelski USCIS 2025';window.location.href='mailto:?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(report)};
$('share').onclick=async()=>{const shareText='Mój wynik w teście USCIS 2025: '+ok+'/'+n+' ('+pct+'%). https://zapytajhanki.com/testy/obywatelstwo-usa/';try{if(navigator.share)await navigator.share({text:shareText});else if(navigator.clipboard){await navigator.clipboard.writeText(shareText);$('share').textContent='Skopiowano!'}else prompt('Skopiuj wynik',shareText)}catch(e){}}
};fetch(URL).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json()}).then(d=>{if(d.questions?.length!==128||d.questions.some(q=>!q.questionPl||!Array.isArray(q.distractors)||q.distractors.length!==3))throw Error('Question bank incomplete');bank=d.questions;home()}).catch(()=>{$('test-app').textContent='Nie udało się załadować pytań. Odśwież stronę.'})})();