SELECT ?item ?itemLabel ?countryCode ?area ?capitalLabel ?continentLabel ?officialWebsite WHERE {
  ?item wdt:P31 wd:Q3624078 ; wdt:P297 ?countryCode ; wdt:P2046 ?area ; wdt:P36 ?capital ; wdt:P30 ?continent ; wdt:P856 ?officialWebsite .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "pl,en". }
}
ORDER BY ?countryCode
LIMIT {{LIMIT}}
OFFSET {{OFFSET}}
