SELECT ?item ?itemLabel ?countryCode ?population ?area ?capitalLabel ?continentLabel WHERE {
  ?item wdt:P31 wd:Q3624078 ; wdt:P297 ?countryCode ; wdt:P1082 ?population ; wdt:P2046 ?area ; wdt:P36 ?capital ; wdt:P30 ?continent .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "pl,en". }
}
ORDER BY ?itemLabel
LIMIT {{LIMIT}}
OFFSET {{OFFSET}}
